/**
 * @description       : Interface for Contact Service Layer
 *
 * @author            : Kunal Karekar
 * @group             : Contact
 * @last modified on  :
 * @last modified by  :
 *
 * Modifications Log
 * Ver   Date         Author                     	       Modification
 * 1.0   05-09-2023   Kunal Karekar					       Initial version
 */
public interface IContactsSvc {
    
    List<Contact> fetchContacts();

}